[package]
name = "collate"
version = "0.1.0"
authors = ["haydnv"]
edition = "2018"
license-file = "LICENSE"
description = "Traits and a data structure to support collation and bisection"
repository = "http://github.com/haydnv/collate"
readme = "README.md"

categories = ["algorithms", "rust-patterns"]
keywords = ["collation", "bisect"]

[dependencies]
